name: Reusable WF - Release

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:

  build-test-package:
    uses: "./.github/workflows/build-test-package.yml"
    secrets: inherit

  create-release:
    needs: ['build-test-package']
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      contents: write
      id-token: write

    steps:

    - uses: actions/checkout@v3

    - name: download artifacts
      uses: actions/download-artifact@v3
      with:
        path: ./tmp

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ needs.build-test-package.outputs.version }}
        commit: ${{ github.sha }}
        name: "howso-engine-no-telemetry ${{ needs.build-test-package.outputs.version }}"
        artifactErrorsFailBuild: true
        generateReleaseNotes: true
        makeLatest: legacy
        artifacts: "./tmp/howso-engine-no-telemetry-*/howso-engine-no-telemetry-*.tar.gz,./tmp/howso_engine_no_telemetry-*/howso_engine_no_telemetry-*.whl"
        artifactContentType: application/gzip

    - name: Clean up dir
      run: |
        mkdir -p dist
        find ./tmp -type f -name '*.whl' -exec cp -t ./dist {} +
        find ./tmp -type f -name '*.tar.gz' -exec cp -t ./dist {} +
        ls ./dist

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1